name: Manual release
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'v1.0.2'  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    - name: Archiving...
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'RAGEMP Optimization Script - ${{ inputs.version }}.zip'
        exclusions: '/.github/* LICENSE'
        
    - name: Creating release...
      id: create_release
      uses: actions/create-release@main
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        arifacts: 'RAGEMP Optimization Script - ${{ inputs.version }}.zip'
        tag_name: ${{ inputs.version }}
        release_name: Release ${{ inputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
