name: Manual release
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'v1.0.2'  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    - name: Archiving...
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'RAGEMP Optimization Script - ${{ inputs.version }}.zip'
        exclusions: '/.github/* LICENSE'
        
    - name: Uploading archive...
      uses: ncipollo/release-action@main
      with:
        artifacts: 'RAGEMP Optimization Script - ${{ inputs.version }}.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
